### PR TITLE
Properly render service alert body and fix retina tile display

### LINKED ISSUE #107: Support service alert body content
Presently, if a GTFS-rt alert has a body value, it is not rendered in the UI. TriMet alerts do not have bodies, so the original UI was designed without a way to render this. Many other agencies *do* have alert bodies, so we need a way to display these.

### PR DESCRIPTION
**Pull request by landonreed**
Fixes #107 and #109.

### CODE REVIEW

File: lib/components/map/base-layers.js [hunk 1]
```diff
@@ -8,16 +9,23 @@ class BaseLayers extends Component {
...
-          <BaseLayer
-            name={l.name}
-            checked={i === 0}
-            key={i}>
-            <TileLayer
-              {...l}
-              detectRetina />
-          </BaseLayer>
-        ))}
+        {baseLayers && baseLayers.map((l, i) => {
```
Comment (evansiroky) [inline lib/components/map/base-layers.js]: Please rename `l` to `layers` since we also have this `L` variable. Maybe even rename `L` to `Leaflet`.

Comment (evansiroky) [reply lib/components/map/base-layers.js]: Actually, is this file even needed anymore? It doesn't appear to be used anywhere. If not we should delete it.
