### PR TITLE
Stop viewer new schedules

### LINKED ISSUE #286: Add table for stop times in schedule view
In the schedule view, the Stop Viewer should list arrivals in chronological order as shown in this mockup:

image

### LINKED ISSUE #287: Stop viewer in schedule mode only shows the first 3 trips for a day.
## Observed behavior

The stop viewer in **Schedule View** only shows the first 3 departures of the selected day sorted by time starting at midnight on each route/pattern that serves a particular stop.

On some routes, post-midnight departure times are shown as first departures, to the top of the schedule, rather than towards the bottom with the last departures of the day.

## TBD Expected behavior

The stop viewer should show either all departures for the day or a limited number of departures starting from around the time indicated in the query and date selected in the stop viewer.

Furthermore, the departure times should be sorted to show times from the beginning of service to the end of service for the selected day in Stop Viewer. For instance, a bus running at a 20-minute frequency from 06:00 to 01:00 at night should display a portion of this sequence: 06:00, 06:20, ... , 23:40, 00:00, 00:20, 00:40, 01:00.

## Steps to reproduce

Go to https://beta-plan.septa.org/#/stop/SEPTA%20Bus:101 and toggle the Schedule Mode on the Stop Viewer.

Example 1 - Only first departures of the day are shown regardless of time of day:
- Observe the departures shown for route 29 (see screenshot below).
- Compare with the published timetable http://septa.org/schedules/bus/pdf/029.pdf (or GTFS equivalent).
- The departures shown are for the first 3 trips in the morning.

The screenshot below was taken at 6pm local time.
image

Example 2 - Incorrect departure order
- Observe the departures shown for route 64 with terminus at 49th (see screenshot below).
- Compare with the published timetable http://septa.org/schedules/bus/pdf/064.pdf (or GTFS equivalent).
- The first departure listed is the 00:14 (12:14 am), which is the last trip of the day.

image

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
This PR fixes #286 and fixes #287 as follows:
- The schedule view by pattern is replaced with a `StopScheduleTable` sorted by departures across all patterns.
- The schedule view scrolls to the first departure from now ~(it will be underneath the stop viewer header)~ and highlights it.
- The underlying API call is changed to use the `/date/` OTP endpoint, removing stop times previously included from the previous service day.
- If `stoptime.headsign` returned by OTP are blank, they are populated using the pattern description from OTP.
- Some common routines are refactored in `utils/viewer.js`, including a new `StopTimeCell` component used by `PatternRow`
- A time zone indicator is shown if user is not in the home timezone config param.
- 

image

Remaining issues
- getStopTimeFormatted needs to be refactored as a component => ~working on this next~ refactored in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/c7e23684606c801429e3ee9b12499f81641293a7.
- The code for schedule view remains in `PatternRow`, will get removed eventiually. => Removed.
- The scroll zone should probably start just under the stop viewer header. Currently, it hides a portion of the scroll zone (the scrollbars extend all the way to the top... any reason to leave as is right now? => Addressed.

image

### CODE REVIEW

**Comment by landonreed** [comment]
One quick comment: for the scrolling, I think we should perhaps have the controls at the top of the stop viewer fixed in place (rather than disappearing when I scroll down the list of arrivals).

**Review by landonreed — CHANGES_REQUESTED** [review]
This is looking pretty good! I have a few more small changes:

File: lib/components/viewers/pattern-row.js [hunk 1]
```diff
@@ -123,6 +119,7 @@ export default class PatternRow extends Component {
     )
   }
 
+  // FIXME: remove
```
[the remark this answers is not in the document]
Comment (binh-dam-ibigroup) [reply lib/components/viewers/pattern-row.js]: I removed this function in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/674de1002ecb4deef9cc341e03a45c209de0f86f.

File: lib/components/viewers/stop-viewer.js [hunk 2]
```diff
@@ -275,6 +276,72 @@ class StopViewer extends Component {
...
+
+    let contents
+    if (!hasStopTimesAndRoutes) {
+      contents = <div>No stop times found for date.</div>
+    } else if (scheduleView) {
+      contents = <StopScheduleTable />
+    } else {
+      contents = (
+        <>
+          <div style={{ marginTop: 20 }}>
```
[the remark this answers is not in the document]
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js]: Extracted in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/c60924d14aa25bf37c5752f7f064cb5efa70de6f.

File: lib/components/viewers/stop-viewer.js [hunk 3]
```diff
@@ -275,6 +276,72 @@ class StopViewer extends Component {
...
+                    key={patternTimes.id}
+                    stopViewerArriving={stopViewerArriving}
+                    homeTimezone={homeTimezone}
+                    timeFormat={timeFormat}
+                  />
+                )
+              })
+            }
+          </div>
+          {!scheduleView
```
[the remark this answers is not in the document]
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js]: Removed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/674de1002ecb4deef9cc341e03a45c209de0f86f.

File: lib/components/viewers/stop-schedule-table.js [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+
+const mapStateToProps = (state, ownProps) => {
+  const { config, transitIndex, ui } = state.otp
+  return {
+    homeTimezone: config.homeTimezone,
+    stopData: transitIndex.stops[ui.viewedStop.stopId],
+    stopViewerArriving: config.language.stopViewerArriving,
+    timeFormat: getTimeFormat(config)
+  }
+}
```
[the remark this answers is not in the document]
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-schedule-table.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/c60924d14aa25bf37c5752f7f064cb5efa70de6f.

File: lib/util/viewer.js [hunk 5]
```diff
@@ -154,9 +186,7 @@ export function getStopTimesByPattern (stopData) {
           times: []
         }
       }
-      const filteredTimes = patternTimes.times.filter(stopTime => {
-        return stopTime.stopIndex < stopTime.stopCount - 1 // ensure that this isn't the last stop
-      })
+      const filteredTimes = patternTimes.times.filter(excludeLastStop)
```
[the remark this answers is not in the document]
Comment (binh-dam-ibigroup) [reply lib/util/viewer.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/389275c528792140cab4756afa2608fa275645b2.

File: lib/util/viewer.js [hunk 6]
```diff
@@ -128,13 +143,30 @@ export function getStatusLabel (delay) {
   )
 }
 
+/**
+ * @returns true if the given stopTime does not correspond to the last stop visited by a pattern.
+ */
+export function excludeLastStop ({ stopIndex, stopCount }) {
+  return stopIndex < stopCount - 1
+}
```
[the remark this answers is not in the document]
Comment (binh-dam-ibigroup) [reply lib/util/viewer.js:81]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/389275c528792140cab4756afa2608fa275645b2.

File: lib/util/viewer.js [hunk 7]
```diff
@@ -185,3 +215,12 @@ export function getModeFromRoute (route) {
   }
   return route.mode || modeLookup[route.type]
 }
+
+/**
+ * Compares departure times of two stops.
+ */
```
[the remark this answers is not in the document]
Comment (binh-dam-ibigroup) [reply lib/util/viewer.js:153]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/4d0d8dd4d808f061851cb474395939830e028934.

**Comment by binh-dam-ibigroup** [comment]
Ready to review again, hopefully.

File: example.css [hunk 8]
```diff
@@ -30,10 +30,14 @@
...
 
+/* Necessary for defining the height in the main panel nested elements. */
+.main-row main {
+  height: 100%;
+}
+
 .sidebar {
   height: 100%;
   padding: 10px;
-  overflow-y: scroll;
```
Comment (landonreed) [inline example.css:36]: I think this is breaking scrolling for all of the viewers...

Comment (landonreed) [reply example.css:36]: Never mind, I just had to restart the app for this to work.

File: lib/components/viewers/stop-schedule-table.js [hunk 9]
```diff
@@ -0,0 +1,152 @@
...
+
+    mergedStopTimes = mergedStopTimes.sort(stopTimeComparator)
+
+    // Find the next stop time that is departing. We will scroll to that stop time entry.
+    let firstDepartureFromNow
+    if (mergedStopTimes.length) {
+      // Search starting from the last stop time (largest seconds until departure) for this pattern.
+      const lastStopTime = mergedStopTimes[mergedStopTimes.length - 1]
+
+      firstDepartureFromNow = mergedStopTimes.reduce((firstStopTime, stopTime) => {
```
Comment (landonreed) [inline lib/components/viewers/stop-schedule-table.js:101]: I'm not a big fan of reduce functions -- I don't find them very user friendly. Could you look into using a different approach?

File: lib/components/viewers/stop-time-cell.js [hunk 10]
```diff
@@ -0,0 +1,146 @@
...
+    departureTime,
+    // Only show timezone (e.g., PDT) if user is not in home time zone (e.g., user
+    // in New York, but viewing a trip planner for service based in Los Angeles).
+    getTimeFormat(timeFormat, homeTimezone)
+  )
+  // We only want to show the day of the week if the arrival is on a
+  // different day and we're not showing the countdown string. This avoids
+  // cases such as when it's Wednesday at 11:55pm and an arrival occurs at
+  // Thursday 12:19am. We don't want the time to read: 'Thursday, 24 minutes'.
+  const showDayOfWeek = !vehicleDepartsToday && !showCountdown
```
Comment (landonreed) [inline lib/components/viewers/stop-time-cell.js:96]: I don't think the day of the week should be shown in scheduledView.

File: lib/components/viewers/stop-time-cell.js [hunk 11]
```diff
@@ -0,0 +1,146 @@
...
+
+  // Use "soon text" (e.g., Due) if vehicle is approaching.
+  const countdownString = secondsUntilDeparture < 60
+    ? soonText
+    : formatDuration(secondsUntilDeparture)
+  const formattedTime = formatSecondsAfterMidnight(
+    departureTime,
+    // Only show timezone (e.g., PDT) if user is not in home time zone (e.g., user
+    // in New York, but viewing a trip planner for service based in Los Angeles).
+    getTimeFormat(timeFormat, homeTimezone)
```
Comment (landonreed) [inline lib/components/viewers/stop-time-cell.js:90]: This doesn't appear to be working for me with the TriMet config `homeTimezone: America/Los_Angeles`.

File: lib/actions/api.js [hunk 12]
```diff
@@ -548,20 +548,30 @@ const findStopTimesForStopError = createAction('FIND_STOP_TIMES_FOR_STOP_ERROR')
...
+    if (date) {
+      const dateWithoutDashes = date.replace(/-/g, '')
+      datePath = `/${dateWithoutDashes}`
+    }
+
     // If other params not provided, fall back on defaults from stop viewer config.
-    const queryParams = { ...getStopViewerConfig(getState().otp), ...otherParams }
-    // If no start time is provided, pass in the current time. Note: this is not
+    // const queryParams = { ...getStopViewerConfig(getState().otp), ...otherParams }
+    // TODO: parform an additional query with ^^ and without date path if the one below returns no stop times at all.
```
Comment (landonreed) [inline lib/actions/api.js:560]: I don't recall what this stopViewerConfig stuff used to do. I am noticing, however, that this PR has changed the behavior of the "live" stop viewer. We should be showing "extra" stop times even if they are not today. I'm not really sure if this is related to fixes you tried to make to address #287 or if it's related to something else.

Using a TriMet config, navigate to http://localhost:9966/#/stop/TriMet:4105 and compare with https://newplanner.trimet.org/map/#/stop/TriMet:4105

## localhost:
image
## newplanner:
image

File: lib/components/viewers/stop-live-table.js [hunk 13]
```diff
@@ -0,0 +1,157 @@
...
+} from '../../util/viewer'
+
+const { getUserTimezone } = coreUtils.time
+
+const defaultState = {
+  spin: false,
+  timer: null
+}
+
+class StopLiveTable extends Component {
```
Comment (landonreed) [inline lib/components/viewers/stop-live-table.js:21]: Maybe a better component name would be `LiveStopArrivalsByPattern`?

File: lib/components/viewers/pattern-row.js [hunk 14]
```diff
@@ -99,7 +101,12 @@ export default class PatternRow extends Component {
...
-                          {getFormattedStopTime(stopTime, homeTimezone, stopViewerArriving, timeFormat)}
+                          <StopTimeCell
+                            homeTimezone={homeTimezone}
+                            soonText={stopViewerArriving}
+                            stopTime={stopTime}
+                            timeFormat={timeFormat}
+                          />
                         </div>
                         <div className='cell status-column'>
                           {stopTime.realtimeState === 'UPDATED'
```
Comment (landonreed) [inline lib/components/viewers/pattern-row.js:112]: Since you've created StopTimeCell, I think it might be useful to create a similar component for `getStatusLabel` below.  Also, it would probably be good to combine the `Scheduled` div as part of the new `StatusLabel` component.

**Review by landonreed — CHANGES_REQUESTED** [review]
A few more changes for this. Also, just created #293 with a few tweaks.

File: lib/components/viewers/stop-schedule-table.js (hunk 9 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-schedule-table.js]: I extracted the method and made it use a plain `forEach` in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/edd5a4bf88907df9d012180bedebaaddbc01d6f8.

File: lib/components/viewers/stop-time-cell.js (hunk 10 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js:80]: Addressed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/edd5a4bf88907df9d012180bedebaaddbc01d6f8.

File: lib/components/viewers/stop-time-cell.js (hunk 11 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: This may be related to https://momentjs.com/docs/#/displaying/format/.

Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: Fixed (temporarily) in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/8ebacce5ee93b982c345db26b44396c6ce1329d6.

image

Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: I have added https://github.com/opentripplanner/otp-ui/issues/230 should we decide to update the library.

Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: Do we want to do anything regarding the layout on the pattern mode now that it shows the timezone? 
image

File: lib/components/viewers/stop-live-table.js (hunk 13 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-live-table.js]: Renamed in. https://github.com/opentripplanner/otp-react-redux/pull/292/commits/4bd58959771c9acc35dd8eeea1bb5e4ace13c818.

File: lib/actions/api.js (hunk 12 above)
Comment (binh-dam-ibigroup) [reply lib/actions/api.js]: Fixed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/fac518e21590d006975dd444f26a0c07d7de7328.

File: lib/components/viewers/stop-time-cell.js (hunk 11 above)
Comment (landonreed) [reply lib/components/viewers/stop-time-cell.js]: Hmm... I didn't think of that. Perhaps, in the interest of removing redundant information, we should change the behavior to show an alert at the top of the stop viewer (just below the "Plan a trip" line) that states that times are in a different timezone (mention the timezone and time diff).

Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: I like this approach too.

File: lib/components/viewers/pattern-row.js (hunk 14 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/pattern-row.js:112]: Let's do that in another PR.

File: lib/components/viewers/stop-time-cell.js (hunk 11 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/daeb6ac3811946167078ea91d3cb39f028c8fe2f.

File: lib/components/viewers/pattern-row.js (hunk 14 above)
Comment (landonreed) [reply lib/components/viewers/pattern-row.js:112]: Part of my rationale for doing it in this PR is that by moving the other JSX code out of the file, we're making `util/viewer.js` more in line with other util files that don't have any React code. If we just go ahead with moving `getStatusLabel`, we'll complete that effort and make the purpose of the util file a little more clear and it will allow us to remove the `React` import.

Comment (binh-dam-ibigroup) [reply lib/components/viewers/pattern-row.js:112]: Two arguments against it:
- Unlike `StopTimeCell`, those changes are about code that was not touched in the course of this PR.
- Those changes will expose DRY opportunities, especially in the `RealTimeTimeColumn` of the `ItineraryBody` component.

What I can do is set up another PR that addresses that, and if we feel the changes are small enough, we can merge that into this PR.

File: lib/util/viewer.js [hunk 15]
```diff
@@ -156,3 +156,53 @@ export function stopTimeComparator (a, b) {
   const bTime = b.serviceDay + b.scheduledDeparture
   return aTime - bTime
 }
+
+/**
+  * Find the stop time corresponding to the first departure
+  * (the closest departure past the current time).
+  */
+export function getFirstDepartureFromNow (mergedStopTimes) {
```
Comment (landonreed) [inline lib/util/viewer.js:164]: This arg should probably just be stopTimes rather than mergedStopTimes.

File: lib/util/viewer.js [hunk 16]
```diff
@@ -156,3 +156,53 @@ export function stopTimeComparator (a, b) {
...
+  // Search starting from the last stop time (largest seconds until departure) for this pattern.
```
Comment (landonreed) [inline lib/util/viewer.js:165]: I think we should probably delete "for this pattern". Might be a vestige from previous code.

File: lib/components/viewers/pattern-row.js (hunk 14 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/pattern-row.js:112]: The PR for the status label is at https://github.com/opentripplanner/otp-react-redux/pull/294.

File: lib/util/viewer.js (hunk 16 above)
Comment (binh-dam-ibigroup) [reply lib/util/viewer.js]: Yeah I missed that one. Fixed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/ced7d9221f0ad6ada60563f452610feb8f9ed297.

File: lib/util/viewer.js (hunk 15 above)
Comment (binh-dam-ibigroup) [reply lib/util/viewer.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/ced7d9221f0ad6ada60563f452610feb8f9ed297.

File: lib/components/viewers/live-stop-times.js [hunk 17]
```diff
@@ -0,0 +1,161 @@
...
+              type='checkbox'
+            />{' '}Auto-refresh arrivals?
+          </label>
+          <button
+            className='link-button pull-right'
+            onClick={this._refreshStopTimes}
+            style={{ fontSize: 'small' }}
+          >
+            <Icon
+              className={spin ? 'fa-spin' : ''}
```
Comment (landonreed) [inline lib/components/viewers/live-stop-times.js:149]: This button no longer spins on click.

File: lib/components/viewers/stop-viewer.js [hunk 18]
```diff
@@ -233,48 +202,64 @@ class StopViewer extends Component {
...
-        patternA.route,
-        patternB.route
-      )
-      if (routeCompareValue !== 0) return routeCompareValue
 
-      // if same route, sort by headsign
-      return patternHeadsignComparator(patternA, patternB)
+    let contents
+    if (!hasStopTimesAndRoutes) {
+      contents = <div>No stop times found for date.</div>
```
Comment (landonreed) [inline lib/components/viewers/stop-viewer.js:236]: "No stop times" flashes now when you click the refresh button.

Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js:236]: It was introduced by [this](https://github.com/opentripplanner/otp-react-redux/pull/292/files#diff-341585469c20207f4fd902aa6736bc338f82783a760ce424a8877c305984a5a1R577) which is what we want for the schedule... but not the live arrivals then.

File: lib/components/viewers/stop-viewer.js [hunk 19]
```diff
@@ -203,16 +154,34 @@ class StopViewer extends Component {
...
     }
+
+    let timezoneWarning
+    if (!inHomeTimezone) {
+      const timezoneCode = moment().tz(homeTimezone).format('z')
+
+      // Display a banner about the departure timezone if user's timezone is not the configured 'homeTimezone'
+      // (e.g. cases where a user in New York looks at a schedule in Los Angeles).
+      timezoneWarning = (
+        <Alert bsStyle='info' style={{ marginBottom: 0, padding: '5px 10px', textAlign: 'center' }}>
```
Comment (landonreed) [inline lib/components/viewers/stop-viewer.js:176]: I think this could use a `margin-top: 5px`. Any reason you opted not to use a styled component?

File: lib/components/viewers/stop-viewer.js [hunk 20]
```diff
@@ -203,16 +154,34 @@ class StopViewer extends Component {
...
+          <Glyphicon glyph='info-sign' /> Departure times
```
Comment (landonreed) [inline lib/components/viewers/stop-viewer.js:177]: "Note: departure times...."

File: lib/components/viewers/stop-viewer.js [hunk 21]
```diff
@@ -233,48 +202,64 @@ class StopViewer extends Component {
...
+      contents = (
+        <StopScheduleTable
+          date={date}
+          homeTimezone={homeTimezone}
+          stopData={stopData}
+          timeFormat={timeFormat}
+        />
+      )
+    } else {
+      contents = (
```
Comment (landonreed) [inline lib/components/viewers/stop-viewer.js:247]: When switching between these views, the times are not re-fetched, which results in some weirdness if you go from some other date (e.g. yesterday) back to "live times".

**Review by landonreed — CHANGES_REQUESTED** [review]
A few more changes: mostly minor degradations from previous functionality.

File: lib/components/viewers/stop-viewer.js (hunk 20 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js:177]: I think the icon and "Note:" are redundant... do you insist on that?

File: lib/components/viewers/stop-viewer.js (hunk 21 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js:256]: Fixed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/08253eff2bb186584000d7209a5635d6de86dbfb

File: lib/components/viewers/stop-viewer.js (hunk 19 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js]: No... Fixed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/08253eff2bb186584000d7209a5635d6de86dbfb.

File: lib/components/viewers/stop-viewer.js (hunk 18 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js:245]: Fixed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/08253eff2bb186584000d7209a5635d6de86dbfb.

File: lib/components/viewers/live-stop-times.js (hunk 17 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/live-stop-times.js:149]: Fixed in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/08253eff2bb186584000d7209a5635d6de86dbfb.

File: lib/actions/api.js [hunk 22]
```diff
@@ -570,11 +570,13 @@ export function findStopTimesForStop (params) {
...
 
-    // Clear existing stop times to prevent extra rendering of stop viewer while schedule is
+    // If reuqested, clear existing stop times to prevent extra rendering of stop viewer while schedule is
     // fetched and a schedule for the same date/stop was shown before. This also has the nice side
     // effect to force a render, initially showing the top row, after changing the schedule view date
     // and all schedules for the new date are the same as the previous date.
-    dispatch(findStopTimesForStopResponse({ stopId, stopTimes: [] }))
+    if (clearData) {
+      dispatch(findStopTimesForStopResponse({ stopId, stopTimes: [] }))
+    }
```
Comment (landonreed) [inline lib/actions/api.js:579]: I didn't notice this before, but this doesn't quite seem like the correct approach. I'd prefer that we send off an action to indicate that we are in a fetching state. The component itself can then read the fetch state from the reducer and determine what to render (rather than making the render behavior stem from the presence/absence of stop data). Currently, changing the date still has the effect of showing a "no stop times" message rather than a loading spinner.

File: lib/components/viewers/stop-viewer.js [hunk 23]
```diff
@@ -32,6 +32,12 @@ const Scrollable = styled.div`
   height: 100%;
   overflow-y: auto;
 `
+// Alert with custom styles
+const StyledAlert = styled(Alert)`
+  margin: 5px 0;
```
Comment (landonreed) [inline lib/components/viewers/stop-viewer.js:37]: Nit: I think this could use 10px on the top.

**Review by landonreed — APPROVED** [review]
Looking good. Conditional approval on the margin fix and merging in #297.

File: lib/components/viewers/stop-viewer.js (hunk 23 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-viewer.js]: Updated with https://github.com/opentripplanner/otp-react-redux/pull/292/commits/98767d35ced6328bc487cdf61e47114d73cfd672.

**Comment by binh-dam-ibigroup** [comment]
This commit https://github.com/opentripplanner/otp-react-redux/pull/292/commits/1cb3ae313dab19137e99a5f6edc18fcdb975bf48 flushes the scrollbar to the right of the stop viewer, but the code is a little dirtier than before, let me know.

image

**Comment by landonreed** [comment]
@binh-dam-ibigroup, the scroll fix is a lot nicer, but I find the code a bit confusing, especially with the multiple `stop-viewer-body` divs. Anyway you can simplify that a bit?

**Comment by binh-dam-ibigroup** [comment]
> @binh-dam-ibigroup, the scroll fix is a lot nicer, but I do find the code a bit confusing, especially with the multiple `stop-viewer-body` divs. Anyway you can simplify that a bit?

I reverted the previous commit and pushed a simpler fix in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/de849dedf2154a4a164ebfa879a3bed3d06180ce.

**Comment by binh-dam-ibigroup** [comment]
I just resolved merge conflicts and added a limit on the width of the 'block id' column.

File: lib/components/viewers/stop-schedule-table.js [hunk 24]
```diff
@@ -118,7 +126,7 @@ class StopScheduleTable extends Component {
             const refProp = scrollToRow ? this.targetDepartureRef : null
             return (
               <tr key={index} className={className} ref={refProp}>
-                <td>{blockId}</td>
+                <BlockCell>{blockId}</BlockCell>
```
Comment (landonreed) [inline lib/components/viewers/stop-schedule-table.js:129]: @binh-dam-ibigroup, since this is using ellipsis overflow, we should add `title={blockId}` to the cell so that on hover a user can view the full value.

Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-schedule-table.js]: Good point. Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/cdf913d9e17f192608e8212a306f436e6680085f.

File: lib/components/viewers/live-stop-times.js [hunk 25]
```diff
@@ -0,0 +1,161 @@
...
+ * stop organized by route pattern.
+ */
+class LiveStopTimes extends Component {
+  state = defaultState
+
+  _refreshStopTimes = () => {
+    const { findStopTimesForStop, viewedStop } = this.props
+    findStopTimesForStop({ stopId: viewedStop.stopId })
+    // TODO: GraphQL approach would just call findStop again.
+    // findStop({ stopId: viewedStop.stopId })
```
Comment (evansiroky) [inline lib/components/viewers/live-stop-times.js:32]: I don't know what this means and it doesn't seem particularly relevant, so seems like a good candidate for comment removal.

File: lib/components/viewers/pattern-row.js [hunk 26]
```diff
@@ -123,91 +130,10 @@ export default class PatternRow extends Component {
...
-  }
-
   render () {
     return (
       <div className='route-row'>
-        {this.props.showScheduleView
-          ? this._renderScheduleView()
-          : this._renderNextArrivalsView()
-        }
+        {this._renderNextArrivalsView()}
```
Comment (evansiroky) [inline lib/components/viewers/pattern-row.js:136]: Seems like the renderNextArrivalsView could be merged into the render function since it is always called only from here.

File: lib/components/viewers/stop-schedule-table.js [hunk 27]
```diff
@@ -0,0 +1,142 @@
...
+  text-align: right;
+  white-space: nowrap;
+`
+
+/**
+ * Table showing scheduled departure times for the specified stop organized
+ * chronologically.
+ */
+class StopScheduleTable extends Component {
+  targetDepartureRef = createRef()
```
Comment (evansiroky) [inline lib/components/viewers/stop-schedule-table.js:59]: Please add a comment about what this is used for.

File: lib/components/viewers/stop-schedule-table.js [hunk 28]
```diff
@@ -0,0 +1,142 @@
...
+
+  render () {
+    const { date, stopData, timeFormat } = this.props
+    // Show loading spinner if times are still being fetched.
+    if (stopData.fetchStatus === FETCH_STATUS.FETCHING) {
+      return <Loading small />
+    }
+    const mergedStopTimes = mergeAndSortStopTimes(stopData)
+
+    // FIXME: Shift today back one day if the current time is between midnight and the end of the service day.
```
Comment (evansiroky) [inline lib/components/viewers/stop-schedule-table.js:88]: Make an issue for this. FIXMEs and TODOs in code comments are not a proper bug and feature tracking system.

File: lib/components/viewers/stop-schedule-table.js [hunk 29]
```diff
@@ -0,0 +1,142 @@
...
+    const shouldHighlightFirstDeparture = mergedStopTimes.length && date === today
+    const highlightedStopTime = shouldHighlightFirstDeparture
+      ? getFirstDepartureFromNow(mergedStopTimes)
+      : null
+
+    return (
+      <StyledTable>
+        <thead>
+          <tr>
+            <th>Block</th>
```
Comment (evansiroky) [inline lib/components/viewers/stop-schedule-table.js:101]: Why include block? I don't think this is useful for transit riders.

File: lib/components/viewers/stop-schedule-table.js [hunk 30]
```diff
@@ -0,0 +1,142 @@
...
+            <th>Departure</th>
+          </tr>
+        </thead>
+        <tbody>
+          {mergedStopTimes.map((stopTime, index) => {
+            const { blockId, headsign, route } = stopTime
+            // Highlight if this row is the imminent departure and schedule is shown for today.
+            const highlightRow = stopTime === highlightedStopTime
+            const className = highlightRow ? 'highlighted-item' : null
+            // FIXME: This is a bit of a hack to account for the sticky table
```
Comment (evansiroky) [inline lib/components/viewers/stop-schedule-table.js:113]: This is a good comment, but should not have a FIXME flag.

File: lib/components/viewers/stop-time-cell.js [hunk 31]
```diff
@@ -0,0 +1,127 @@
...
+   * scheduled time for departures within an hour.
+   */
+  useCountdown: PropTypes.bool,
+  /** Whether to use scheduled departure (otherwise uses realtime) */
+  useSchedule: PropTypes.bool
+}
+
+StopTimeCell.defaultProps = {
+  homeTimezone: null,
+  showIcon: true,
```
Comment (evansiroky) [inline lib/components/viewers/stop-time-cell.js:121]: This is never false. Can this prop be removed entirely?

File: lib/components/viewers/stop-time-cell.js [hunk 32]
```diff
@@ -0,0 +1,127 @@
...
+  soonText: 'Due',
+  useCountdown: true,
```
Comment (evansiroky) [inline lib/components/viewers/stop-time-cell.js:123]: This is never false. Can this prop be removed entirely?

File: lib/components/viewers/stop-time-cell.js [hunk 33]
```diff
@@ -0,0 +1,127 @@
...
+  useSchedule: false
```
Comment (evansiroky) [inline lib/components/viewers/stop-time-cell.js:124]: This is never true. Can this prop be removed entirely?

**Review by evansiroky — CHANGES_REQUESTED** [review]
Has a merge conflict and I have a few ideas on little things to change.

File: lib/components/viewers/stop-time-cell.js (hunk 33 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: Good catch. Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c.

File: lib/components/viewers/stop-time-cell.js (hunk 32 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c.

File: lib/components/viewers/stop-time-cell.js (hunk 31 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-time-cell.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c.

File: lib/components/viewers/stop-schedule-table.js (hunk 30 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-schedule-table.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c.

File: lib/components/viewers/stop-schedule-table.js (hunk 28 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-schedule-table.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c.

File: lib/components/viewers/stop-schedule-table.js (hunk 27 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-schedule-table.js:62]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c

File: lib/components/viewers/pattern-row.js (hunk 26 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/pattern-row.js]: Updated in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c.

File: lib/components/viewers/live-stop-times.js (hunk 25 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/live-stop-times.js]: It is copy paste from exiting code. I removed the comment in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/bb270a7041700a19cc42eebf190a88fc04b0214c.

File: lib/components/viewers/stop-schedule-table.js (hunk 29 above)
Comment (binh-dam-ibigroup) [reply lib/components/viewers/stop-schedule-table.js]: Whether the block column is shown is configurable in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/1c08e0c10a453905bcfcbe1a04763d1828b16506.

**Comment by binh-dam-ibigroup** [comment]
Ready to review once more.

**Review by evansiroky — APPROVED** [review]

File: example-config.yml [hunk 34]
```diff
@@ -200,3 +200,18 @@ itinerary:
...
+#   numberOfDepartures: 3
+#   # Whether to display block IDs with each departure in the schedule mode.
+#   # (defaults to false if unspecified).
+#   showBlockIds: false
+#   # Specifies the time window, in seconds, in which to search for next arrivals,
+#   # so that, for example, if it is Friday and a route does
+#   # not begin service again until Monday, we are showing its next
+#   # departure and it is not entirely excluded from display
+#   # (defaults to 4 days/345600s if unspecified).
+#   timeRange: 345600
```
Comment (landonreed) [inline example-config.yml:217]: Thanks for adding this!

File: lib/reducers/create-otp-reducer.js [hunk 35]
```diff
@@ -74,6 +74,8 @@ export function getInitialState (userDefinedConfig, initialQuery) {
     routingTypes: [],
     stopViewer: {
       numberOfDepartures: 3, // per pattern
+      // Hide block ids unless explicitly enabld in config.
```
Comment (landonreed) [inline lib/reducers/create-otp-reducer.js:77]: typo: enabld

**Review by landonreed — APPROVED** [review]
Looks good! Just a small typo and merge conflict (probably from the `onTimeThresholdSeconds` merge).

File: lib/reducers/create-otp-reducer.js (hunk 35 above)
Comment (binh-dam-ibigroup) [reply lib/reducers/create-otp-reducer.js]: Oh, the spellchecker did not catch that @evansiroky!?
