### PR TITLE
fix(routingQuery): Properly revert to list view after planning trip.

### LINKED ISSUE #373: Batch Trips: Revert to list view after re-planning trip
1. Plan trip: https://atl-rides.ibi-transit.com/#/?fromPlace=Peachtree%20Center&toPlace=Midtown
2. Select option.
2. Change date. Click plan button.
3. View that the first option is selected (we should return to list view).

### PR DESCRIPTION
**Pull request by philip-cline**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description
fix #373 

Currently, if an option is selected, the batch trips Itinerary View will not revert to the default list view but will instead show the full expanded option. To duplicate these steps:
Plan trip: https://atl-rides.ibi-transit.com/#/?fromPlace=Peachtree%20Center&toPlace=Midtown
Select option.
Change date. Click plan button.
View that the first option is selected (we should return to list view).

To fix this, when a valid routingQuery is made, the itinerary view is now set to DEFAULT. Note the ItineraryView options include two options for 'list' view (DEFAULT and LIST).

### CODE REVIEW

**Review by binh-dam-ibigroup — APPROVED** [review]
Thanks for fixing this bug!

**Comment by philip-cline** [comment]
Just tagging @evansiroky if you have any input here.

File: lib/actions/ui.js [hunk 1]
```diff
@@ -240,6 +240,7 @@ export const MobileScreens = {
  * (currently only used in batch results).
  */
 export const ItineraryView = {
+  /** FIXME: Duplicate value for 'list', DEFAULT and LIST */
   DEFAULT: 'list',
```
Comment (landonreed) [inline lib/actions/ui.js:244]: @evansiroky and @binh-dam-ibigroup, do you see any reason to maintain `LIST` and `DEFAULT` (which both have `list` as their value)? I'm of the mind that we should maybe just entirely replace `DEFAULT` with `LIST`, but wanted to get your feedback in case there was a good reason to keep `DEFAULT`.

Comment (binh-dam-ibigroup) [reply lib/actions/ui.js:244]: The alternative would be to replace the DEFAULT entry with
```js
const DEFAULT_ITINERARY_VIEW = ItineraryView.LIST
```
(Whether the view state is default determines whether the `ui_itineraryView` parameter is added to the URL).

Comment (evansiroky) [reply lib/actions/ui.js:244]: I'm in favor of removing DEFAULT completely as it'd be more explicit.

**Review by evansiroky — APPROVED** [review]

File: lib/actions/ui.js (hunk 1 above)
Comment (landonreed) [reply lib/actions/ui.js:244]: @philip-cline, could you move forward with removing the `DEFAULT` option and replacing with `LIST`?

**Review by landonreed — APPROVED** [review]
Approved on the condition that `DEFAULT` is removed from `ItineraryView`.
