### PR TITLE
Geocoding fixes

### LINKED ISSUE #180: Handle ungeocoded from and to places when parsing query params
Some transit agencies have simple forms on their website that connect with Google Transit/Maps by sending the place names, time, and date. otp-react-redux should accommodate the same kind of thing, by simply attempting to geocode the incoming place names when parsing the query params.

### PR DESCRIPTION
**Pull request by landonreed**
This PR fixes #180 and #181. It is intended for `master` because it contains maintenance changes for an existing implementation, but we should also ensure that the changes make their way into the otp-ui side of things.

To test the geocoding of ungeocoded place names:
1. use the SEPTA config
2. `yarn start`
3. Visit http://localhost:9966/#/?fromPlace=wells%20fargo%20center&toPlace=strawberry%20mansion

### CODE REVIEW

File: lib/util/query.js [hunk 1]
```diff
@@ -148,22 +149,52 @@ export function getDefaultQuery (config) {
   return defaultQuery
 }
 
+/**
+ * Geocode utility for returning the first result for the provided place name text.
+ * @param  {String} text - text to search
+ * @param  {Object} geocoderConfig
+ * @return {Location}
+ */
+async function getFirstGeocodeResult (text, geocoderConfig) {
```
Comment (binh-dam-ibigroup) [inline lib/util/query.js:158]: Is the underlying geocoder API async?

File: lib/util/query.js [hunk 2]
```diff
@@ -148,22 +149,52 @@ export function getDefaultQuery (config) {
...
         query.from = parseLocationString(params.fromPlace)
+        // If a valid location was not found, but the place name text exists,
+        // attempt to geocode the name.
+        if (!query.from && params.fromPlace) {
+          query.from = await getFirstGeocodeResult(params.fromPlace, config.geocoder)
+        }
         break
       case 'toPlace':
         query.to = parseLocationString(params.toPlace)
+        // If a valid location was not found, but the place name text exists,
```
Comment (binh-dam-ibigroup) [inline lib/util/query.js:193]: Add a TODO comment to note potential for combining the code of these two cases.

File: lib/util/query.js (hunk 1 above)
Comment (landonreed) [reply lib/util/query.js:158]: The geocoder API makes asynchronous fetches, so if we want to be able to use the result inline (instead of in a then clause), we need to make this function async.

File: lib/util/query.js (hunk 2 above)
Comment (landonreed) [reply lib/util/query.js:193]: Fixed.
